#!/usr/bin/env bash
# install/aider.sh — Install and set up Aider
set -euo pipefail

CYAN='\033[0;36m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BOLD='\033[1m'; RESET='\033[0m'

echo ""
echo -e "${CYAN}${BOLD}═══════════════════════════════════════${RESET}"
echo -e "${CYAN}${BOLD}   Installing Aider                     ${RESET}"
echo -e "${CYAN}${BOLD}═══════════════════════════════════════${RESET}"
echo ""

# ─── Check for Python ─────────────────────────────────────────────────────────
if ! command -v python3 &>/dev/null; then
  echo -e "${RED}✖ Python 3 is required but not installed.${RESET}"
  echo "Install from https://python.org (v3.10 or higher required)"
  exit 1
fi

py_version=$(python3 --version | awk '{print $2}' | cut -d. -f1-2)
py_major=$(echo "$py_version" | cut -d. -f1)
py_minor=$(echo "$py_version" | cut -d. -f2)
if ! [[ "$py_major" =~ ^[0-9]+$ && "$py_minor" =~ ^[0-9]+$ ]]; then
  echo -e "${RED}✖ Could not determine Python version. Install Python 3.10 or higher.${RESET}"
  exit 1
fi
if (( py_major < 3 || (py_major == 3 && py_minor < 10) )); then
  echo -e "${RED}✖ Python 3.10+ required. Found ${py_version}.${RESET}"
  echo "Install from https://python.org"
  exit 1
fi
echo -e "${GREEN}✔ Python ${py_version} detected${RESET}"

# ─── Install Aider ────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}Installing Aider via pip...${RESET}"

if command -v pipx &>/dev/null; then
  echo "(using pipx for isolated install)"
  pipx install aider-chat
else
  pip3 install --upgrade aider-chat
fi

if command -v aider &>/dev/null; then
  echo -e "${GREEN}✔ Aider installed: $(aider --version 2>/dev/null || echo 'ok')${RESET}"
else
  echo -e "${YELLOW}⚠ 'aider' not found in PATH. You may need to restart your terminal.${RESET}"
  echo "If you used pip, try: pip3 install --user aider-chat"
fi

# ─── API Key Setup ────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}⚠ Aider works with multiple model providers. Set at least one API key:${RESET}"
echo ""
echo "  Anthropic Claude (recommended):"
echo "    export ANTHROPIC_API_KEY=\"your-key-here\""
echo ""
echo "  OpenAI:"
echo "    export OPENAI_API_KEY=\"your-key-here\""
echo ""
echo "  Add the export line to ~/.zshrc or ~/.bashrc to make it permanent."
echo ""

# ─── Agent Config Setup ───────────────────────────────────────────────────────
echo -e "${BOLD}Setting up Aider config...${RESET}"
if [[ ! -f ".aider.conf.yml" ]]; then
  cat > .aider.conf.yml <<AIDERCONF
# Aider configuration — generated by build-your-agent
# model: claude-opus-4-5      # Uncomment to set default model
# auto-commits: false         # Uncomment to disable auto-commits
AIDERCONF
  echo -e "${GREEN}✔ Created .aider.conf.yml${RESET}"
fi

echo ""
echo -e "${CYAN}${BOLD}Next Steps:${RESET}"
echo "  1. Set your API key (see above)"
echo "  2. In your project directory, run:"
echo "     aider --model claude-opus-4-5"
echo "  3. To use your agent as a system prompt:"
echo "     aider --system-prompt your-agent.md"
echo "  4. Docs: https://aider.chat/docs"
echo ""
